# Form implementation generated from reading ui file 'backup_wgt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BackupWidget(object):
    def setupUi(self, BackupWidget):
        BackupWidget.setObjectName("BackupWidget")
        BackupWidget.resize(1143, 955)
        self.verticalLayout = QtWidgets.QVBoxLayout(BackupWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_add_path = QtWidgets.QPushButton(parent=BackupWidget)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro ExtraLight")
        font.setPointSize(12)
        self.btn_add_path.setFont(font)
        self.btn_add_path.setObjectName("btn_add_path")
        self.horizontalLayout_4.addWidget(self.btn_add_path)
        self.btn_realtime_backup = QtWidgets.QPushButton(parent=BackupWidget)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro ExtraLight")
        font.setPointSize(12)
        self.btn_realtime_backup.setFont(font)
        self.btn_realtime_backup.setObjectName("btn_realtime_backup")
        self.horizontalLayout_4.addWidget(self.btn_realtime_backup)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_path = QtWidgets.QListWidget(parent=BackupWidget)
        self.listWidget_path.setMinimumSize(QtCore.QSize(0, 480))
        self.listWidget_path.setObjectName("listWidget_path")
        self.verticalLayout_2.addWidget(self.listWidget_path)
        self.text_console = QtWidgets.QPlainTextEdit(parent=BackupWidget)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro ExtraLight")
        font.setPointSize(12)
        self.text_console.setFont(font)
        self.text_console.setObjectName("text_console")
        self.verticalLayout_2.addWidget(self.text_console)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(BackupWidget)
        QtCore.QMetaObject.connectSlotsByName(BackupWidget)

    def retranslateUi(self, BackupWidget):
        _translate = QtCore.QCoreApplication.translate
        BackupWidget.setWindowTitle(_translate("BackupWidget", "Form"))
        self.btn_add_path.setText(_translate("BackupWidget", "新增备份"))
        self.btn_realtime_backup.setText(_translate("BackupWidget", "实时备份"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BackupWidget = QtWidgets.QWidget()
    ui = Ui_BackupWidget()
    ui.setupUi(BackupWidget)
    BackupWidget.show()
    sys.exit(app.exec())
